# Generated by Django 2.1.7 on 2019-08-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('accessoriesno', models.CharField(db_column='accessoriesNo', max_length=8, primary_key=True, serialize=False)),
                ('accessories', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'accessories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('actionno', models.CharField(db_column='actionNo', max_length=8, primary_key=True, serialize=False)),
                ('likes', models.BooleanField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'action',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=100)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField()),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('is_superuser', models.BooleanField()),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('clothesno', models.CharField(db_column='clothesNo', max_length=8, primary_key=True, serialize=False)),
                ('clothes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clothes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coat',
            fields=[
                ('coatno', models.CharField(db_column='coatNo', max_length=8, primary_key=True, serialize=False)),
                ('coat', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'coat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Meminform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], default='M', max_length=2)),
                ('birth', models.DateField(blank=True, null=True)),
                ('mempic', models.ImageField(blank=True, upload_to='mempics')),
                ('height', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'memInform',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pants',
            fields=[
                ('pantsno', models.CharField(db_column='pantsNo', max_length=8, primary_key=True, serialize=False)),
                ('pants', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=8)),
                ('time', models.DateTimeField(auto_now=True)),
                ('word', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='photos')),
            ],
            options={
                'db_table': 'post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('shoesno', models.CharField(db_column='shoesNo', max_length=8, primary_key=True, serialize=False)),
                ('shoes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shoes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('styleno', models.CharField(db_column='styleNo', max_length=8, primary_key=True, serialize=False)),
                ('style', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'style',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sysdiagrams',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('principal_id', models.IntegerField()),
                ('diagram_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('definition', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sysdiagrams',
                'managed': False,
            },
        ),
    ]
