# Generated by Django 2.1.7 on 2019-11-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwear', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postanalysisview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(blank=True, max_length=12, null=True)),
                ('photo', models.CharField(blank=True, max_length=100, null=True)),
                ('time', models.DateTimeField()),
                ('word', models.CharField(blank=True, max_length=255, null=True)),
                ('ownaccount', models.IntegerField(blank=True, db_column='ownAccount', null=True)),
            ],
            options={
                'db_table': 'postAnalysisView',
                'managed': False,
            },
        ),
    ]
