# Generated by Django 2.1.7 on 2019-09-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwear', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('fono', models.AutoField(db_column='FoNo', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'follow',
                'managed': False,
            },
        ),
    ]
