# Generated by Django 2.1.7 on 2019-12-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwear', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webandusersentenceanalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('websentenceno', models.IntegerField(db_column='webSentenceNo')),
                ('web', models.CharField(blank=True, max_length=100, null=True)),
                ('webtitle', models.CharField(blank=True, db_column='webTitle', max_length=100, null=True)),
                ('sentence', models.CharField(blank=True, max_length=100, null=True)),
                ('ownaccount', models.CharField(blank=True, db_column='ownAccount', max_length=255, null=True)),
            ],
            options={
                'db_table': 'webAndUserSentenceAnalysis',
                'managed': False,
            },
        ),
    ]
